- app/controllers/api/v1/tickets_controller.rb
- app/models/ticket.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20190713225809_add_defaults.rb
- db/schema.rb
- spec/requests/api/v1/ticket_spec.rb
request: localhost:3000/api/v1/tickets
response:
```json
[
{
"id": 1,
"user_id": 1,
"notes": "needs oil change",
"created_at": "2019-07-14T17:02:17.064Z",
"updated_at": "2019-07-14T17:02:17.064Z",
"active": true
},
{
"id": 2,
"table_key": 2,
"user_id": 1,
"notes": "needs new transmission",
"created_at": "2019-07-14T19:14:06.804Z",
"updated_at": "2019-07-14T19:14:06.804Z",
"active": true
},
{
"id": 3,
"table_key": 3,
"user_id": 1,
"notes": "needs new top",
"priority": "medium",
"created_at": …
```
> Get all tickets

- app/controllers/api/v1/resources/tickets_controller.rb
- app/models/ticket.rb
- config/routes.rb
- spec/requests/api/v1/resources/ticket_spec.rb
request: GET /api/v1/resources/:resource_id/tickets
response
```javascript
[
{
"id": 1,
"user_id": 1,
"notes": "needs oil change",
"created_at": "2019-07-14T17:02:17.064Z",
"updated_at": "2019-07-14T17:02:17.064Z",
"active": true
}
]
```
closes #27
> Resource tickets

- app/controllers/api/v1/resources/tickets_controller.rb
- config/routes.rb
- spec/requests/api/v1/resources/tickets/show_spec.rb
request: get localhost:3000/api/v1/resources/1/tickets/1
response:
```json
{
"id": 1,
"user_id": 1,
"notes": "needs oil change",
"created_at": "2019-07-14T17:02:17.064Z",
"updated_at": "2019-07-14T17:02:17.064Z",
"active": true
}
```
closes #28
> Resource ticket show

- app/controllers/api/v1/resources_controller.rb
- app/models/resource.rb
- config/routes.rb
- spec/models/resource_spec.rb
- spec/requests/api/v1/resources/create_spec.rb
- spec/requests/api/v1/resources/index_spec.rb
- spec/requests/api/v1/resources/show_spec.rb
- spec/requests/api/v1/resources/update_spec.rb
This adds the index, show, create, and update actions for Resources
- specs were created for all
- one is skipped for now
- some have sad path functionality
- routes were created
- ResourcesController was created
- model methods were created to find active resource(s)
This also adds belongs_to :user and belongs_to :resource_type in the Resource model because a resource should not exist unless it is tied to a type and a user.
Coverage is at 97.6% because of the skipped test
> 1resources endpoint

- app/controllers/api/v1/resource_types_controller.rb
- app/models/resource_type.rb
- config/routes.rb
- spec/requests/api/v1/resource_types/create_spec.rb
- spec/requests/api/v1/resource_types/index_spec.rb
- spec/requests/api/v1/resource_types/show_spec.rb
- spec/requests/api/v1/resource_types/update_spec.rb
Adds create, index, show, update actions for resource types.
------------------------------------------------------------------
get localhost:3000/api/v1/resource_types/1
response
```json
{
"id": 1,
"category": "vehicle",
"company": "Brew Bears",
"contact_number": null,
"contact_name": null,
"manual_url": null,
"active": true,
"created_at": "2019-07-14T16:59:24.943Z",
"updated_at": "2019-07-14T16:59:24.943Z"
}
```
------------------------------------------------------------------
get localhost:3000/api/v1/resource_types
response
```json
[
{
"id": 1,
"category": "vehicle",
"company": "Brew Bears",
"contact_number": null,
"contact_name": null,
"manual_url": null,
"active": true,
"created_at": "2019-07-14T16:59:24.943Z",
"updated_at": "2019-07-14T16:59:24.943Z"
},
{
"id": 2,
"category": …
```
> Resource types

- app/controllers/api/v1/users_controller.rb
- config/routes.rb
- spec/requests/api/v1/resource_types/create_spec.rb
- spec/requests/api/v1/resource_types/index_spec.rb
- spec/requests/api/v1/resource_types/update_spec.rb
- spec/requests/api/v1/users/create_spec.rb
- spec/requests/api/v1/users/show_spec.rb
Adds show, create, update routes, actions, and spec for Users.
Changes phone numbers to integers in other spec files.
Also adds destroy_all to resource_types.
> 1users endpoint

- .gitignore
- app/controllers/api/v1/resource_types_controller.rb
- app/controllers/api/v1/resources/notes_controller.rb
- app/controllers/api/v1/resources/tickets_controller.rb
- app/controllers/api/v1/resources_controller.rb
- config/database.yml
- config/routes.rb
- spec/requests/api/v1/resource_types/update_spec.rb
- spec/requests/api/v1/resources/tickets/update_spec.rb
- spec/requests/api/v1/resources/update_spec.rb
request: localhost:3000/api/v1/resources/1/tickets/1?notes=changed notes
request
```json
{
"id": 1,
"user_id": 1,
"notes": "changed notes",
"created_at": "2019-07-14T17:02:17.064Z",
"updated_at": "2019-07-16T01:47:10.174Z",
"active": true
}
```
Closes #30
> Patch resource tickets

- .ebextensions/db_seed.config
https://www.allcloud.io/how-to/how-to-run-rake-dbseed-in-amazon-elastic-beanstalk/
(Rachel said this wouldn't blow up my computer)
> This adds the config file to seed the database

- .ebextensions/db_seed.config
Changes config to container_commands: with db:seed etc.
> Changes config to container_commands from amazon forums

- app/controllers/api/v1/resource_types_controller.rb
- app/controllers/api/v1/resources_controller.rb
- app/models/resource.rb
- app/models/resource_type.rb
- app/models/ticket.rb
- spec/models/note_spec.rb
- spec/models/resource_spec.rb
- spec/models/resource_type_spec.rb
- spec/models/ticket_spec.rb
- spec/requests/api/v1/parts/create_spec.rb
Adds class method tests for all models
Increases test coverage to 99.19%
@carriewalsh - I changed the ticket class methods to only pull from one table.
def self.tickets_by_resource(resource_id)
where(table_key: resource_id)
.where(table_name: "Resources")
end
> Model method tests

- app/controllers/api/v1/resource_types_controller.rb
- app/controllers/api/v1/resources_controller.rb
- app/controllers/api/v1/tickets_controller.rb
- app/models/resource.rb
- app/models/resource_type.rb
- app/models/ticket.rb
- spec/models/note_spec.rb
- spec/models/resource_spec.rb
- spec/models/resource_type_spec.rb
- spec/models/ticket_spec.rb
- spec/requests/api/v1/parts/create_spec.rb
search by table name and active status
request: localhost:3000/api/v1/tickets?table=resources&active=true
response: 
```json
[
{
"id": 2,
"table_key": 2,
"user_id": 1,
"notes": "needs new transmission",
"created_at": "2019-07-14T19:14:06.804Z",
"updated_at": "2019-07-14T19:14:06.804Z",
"active": true
},
{
"id": 3,
"table_key": 3,
"user_id": 1,
"notes": "needs new top",
"priority": "medium",
"created_at": "2019-07-14T19:14:09.195Z",
"updated_at": "2019-07-14T19:14:09.195Z",
"active": true
},
{
"id": 1,
"user_id": 1,
"notes": "changed notes",
"frequency_unit": …
```
> Query params

- .circleci/config.yml
Co-authored-by: Carrie Walsh <43975624+carriewalsh@users.noreply.github.com>
Why is this change necessary?
*continuous integration
> Commit Message: Adds the configuration file for CircleCI

- .circleci/config.yml
Co-authored-by: Carrie Walsh <43975624+carriewalsh@users.noreply.github.com>
there was a .yml issue due to syntax.
> CicleCI config

- .circleci/config.yml
Co-authored-by: Carrie Walsh <43975624+carriewalsh@users.noreply.github.com>
Why is this change necessary?
*needed to change the yml file to include proper db setup
> Commit Message: CircleCI db setup

- .ebextensions/db_seed.config
This is where the error was because there was a key without a value still in there.
> Hashes out all of db_seed.config

- Gemfile
- Gemfile.lock
- config/initializers/cors.rb
Will need to change for security in the future.
> Adds cors-rack gem and adds config to cors.rb

- .circleci/config.yml
- Gemfile
- Gemfile.lock
Co-authored-by: Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>
> Adds indents in yml because of build error

- README.md
Currently has all routes.
This includes GET Tickets /api/v1/tickets
> Adds all current endpoint documentation

- Gemfile
- app/controllers/api/v1/resources/parts_controller.rb
- app/controllers/api/v1/resources/tickets_controller.rb
- app/models/part.rb
- config/initializers/cors.rb
- config/routes.rb
- spec/requests/api/v1/parts/create_spec.rb
- spec/requests/api/v1/parts/index_spec.rb
- spec/requests/api/v1/parts/show_spec.rb
- spec/requests/api/v1/parts/update_spec.rb
- spec/requests/api/v1/resources/parts/create_spec.rb
- spec/requests/api/v1/resources/parts/index_spec.rb
- spec/requests/api/v1/resources/parts/show_spec.rb
- spec/requests/api/v1/resources/parts/update_spec.rb
- spec/requests/api/v1/resources/tickets/create_spec.rb
- spec/requests/api/v1/resources/tickets/index_spec.rb
Adds destroy all to api/v1/parts endpoint tests
Adds configuration for CircleCI
Adds endpoints for resource_parts
-------------------------------------
request: get localhost:3000/api/v1/resources/1/parts
response: 
```json
[
{
"id": 6,
"name": "Tank valve",
"inventory": 1,
"active": true,
"created_at": "2019-07-17T20:45:29.818Z",
"updated_at": "2019-07-17T20:49:14.040Z"
},
{
"id": 7,
"name": "bottle opener",
"inventory": 3,
"active": true,
"created_at": "2019-07-17T20:50:43.491Z",
"updated_at": "2019-07-17T20:50:43.491Z"
}
]
```
-------------------------------------
request: get localhost:3000/api/v1/resources/1/parts/6
response: 
```json
{
"id": 6,
"name": "Tank valve",
"inventory": 1,
"active": true,
"created_at": "2019-07-17T20:45:29.818Z",
"updated_at": "2019-07-17T20:49:14.040Z"
} …
```
> Resource parts

- app/models/ticket.rb
- db/migrate/20190718012130_add_status.rb
- db/schema.rb
- spec/requests/api/v1/resources/tickets/show_spec.rb
- spec/requests/api/v1/tickets/show_spec.rb
Closes #86 
enum status: { received:0 , in_progress: 1, fulfilled:2 , cancelled:3}
> Adds status as an enum to the tickets table

- README.md
Co-authored-by: Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>
> Fixes more issues with README

- app/controllers/api/v1/resources/notes_controller.rb
- app/controllers/api/v1/resources/tickets_controller.rb
- app/controllers/api/v1/resources_controller.rb
- app/controllers/api/v1/tickets_controller.rb
- app/serializers/note_serializer.rb
- app/serializers/resource_serializer.rb
- app/serializers/ticket_serializer.rb
- app/serializers/user_serializer.rb
- spec/requests/api/v1/resources/index_spec.rb
- spec/requests/api/v1/resources/notes/index_spec.rb
- spec/requests/api/v1/resources/notes/show_spec.rb
- spec/requests/api/v1/resources/show_spec.rb
- spec/requests/api/v1/resources/tickets/index_spec.rb
- spec/requests/api/v1/resources/tickets/show_spec.rb
- spec/requests/api/v1/tickets/index_spec.rb
- spec/requests/api/v1/tickets/show_spec.rb
- spec/requests/api/v1/users/update_spec.rb
- spec/serializers/note_serializer_spec.rb
- spec/serializers/resource_serializer_spec.rb
- spec/serializers/ticket_serializer_spec.rb
- spec/serializers/user_serializer_spec.rb
Creates user, ticket, note, and resource serializers
Adds serializers to index and show for tickets(namespaced and not), notes, and resources
Adds spec for serializers
Changes specs to match new serializing format.
Fails CircleCI because there is a test written that depends on current_user which currently sits in a different PR
> 1serializers

- app/controllers/api/v1/sessions_controller.rb
- spec/requests/api/v1/sessions/create_spec.rb
Un-nests sessions post output and adds spec
> Changes sessions post output and adds spec
